export const data = {
	personal: {
		name: "Anakin Skywalker",
		status: "single",
		position: "Web Developer",
		address: "Tattoine,Outer Rim",
		phone: "1234567890",
		email: "anakinskywalker@gmail.com",
		img: "https://wallpapercave.com/wp/wp5709607.jpg",
	},
	navLinks: [
		{ title: "Home", path: "#home" },
		{ title: "About", path: "#about" },
		{ title: "Projects", path: "#projects" },
		{ title: "Contact", path: "#contact" },
	],
	education: {
		id: "education",
		title: "My Education",
		description: "My Learning Path",
		data: [
			{
				date: "2015",
				course: "High School",
				institute: "The Best School",
				place: "tattoine",
			},
			{
				date: "2017",
				course: "Diploma in Computer Science",
				institute: "The Best College",
				place: "tattoine",
			},
			{
				date: "2020",
				course: "Bachelor's Degree in Computer Science",
				institute: "The Great College",
				place: "tattoine",
			},
			{
				date: "2024",
				course: "Master's Degree in Computer Science",
				institute: "The Great College",
				place: "tattoine",
			},
		],
	},
	about: {
		id: "about",
		title: "ABOUT ME",
		description:
			"Hi, I'm Anakin Skywalker, a dynamic full-stack developer driven by a passion for crafting cutting-edge digital solutions. With expertise across the entire development stack, I specialize in building scalable back-end systems using technologies like Node.js and Django, complemented by proficiency in modern front-end frameworks like React and Vue.js. Experienced in database management, I ensure efficient data handling with both relational and NoSQL databases. Embracing DevOps principles, I streamline development processes for seamless integration and deployment. A natural problem solver, I excel in troubleshooting and thrive in collaborative environments. Committed to continuous learning, I stay ahead in this ever-evolving tech landscape. Let's connect and discuss how I can contribute to your project!",
	},
	contact: {
		id: "contact",
		title: "CONTACT ME",
		description: "Let's Discuss What You Want?",
	},
	features: {
		id: "features",
		title: "Features",
		description: "I'm Best At",
		data: [
			{ id: 1, title: "CLEAN CODE", desc: "" },
			{ id: 2, title: "REUSABLE COMPONENTS", desc: "" },
			{ id: 3, title: "RESPONSIVE DESIGN", desc: "" },
		],
	},
	hero: {
		id: "home",
		title: "Home",
		headingOne: "I'm Hrishik,",
		headingTwo: "I'm A Web Developer.",
	},
	intro: {
		id: "intro",
		title: "Intro",
		data: ["I CREATE", "COOL", "WEB APPS"],
	},
	projects: {
		id: "projects",
		title: "MY PROJECTS",
		data: [
			{
				id: 1,
				title: "project one",
				img: "https://images.pexels.com/photos/210158/pexels-photo-210158.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2015",
				code: "",
				url: "",
			},
			{
				id: 2,
				title: "project two",
				img: "https://images.pexels.com/photos/414860/pexels-photo-414860.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2016",
				code: "",
				url: "",
			},
			{
				id: 3,
				title: "project three",
				img: "https://images.pexels.com/photos/175771/pexels-photo-175771.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2017",
				code: "",
				url: "",
			},
			{
				id: 4,
				title: "project four",
				img: "https://images.pexels.com/photos/296324/pexels-photo-296324.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2018",
				code: "",
				url: "",
			},
			{
				id: 5,
				title: "project five",
				img: "https://images.pexels.com/photos/3862601/pexels-photo-3862601.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2019",
				code: "",
				url: "",
			},
			{
				id: 6,
				title: "project six",
				img: "https://images.pexels.com/photos/562211/pexels-photo-562211.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2020",
				code: "",
				url: "",
			},
			{
				id: 7,
				title: "project seven",
				img: "https://images.pexels.com/photos/247676/pexels-photo-247676.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2021",
				code: "",
				url: "",
			},
			{
				id: 8,
				title: "project eight",
				img: "https://images.pexels.com/photos/7709017/pexels-photo-7709017.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2022",
				code: "",
				url: "",
			},
			{
				id: 9,
				title: "project nine",
				img: "https://images.pexels.com/photos/8386367/pexels-photo-8386367.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2023",
				code: "",
				url: "",
			},
			{
				id: 10,
				title: "project ten",
				img: "https://images.pexels.com/photos/8386429/pexels-photo-8386429.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2024",
				code: "",
				url: "",
			},
			{
				id: 11,
				title: "project eleven",
				img: "https://images.pexels.com/photos/8386367/pexels-photo-8386367.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2023",
				code: "",
				url: "",
			},
			{
				id: 12,
				title: "project twelve",
				img: "https://images.pexels.com/photos/8386429/pexels-photo-8386429.jpeg?auto=compress&cs=tinysrgb&w=600",
				tools: "HTML/CSS/JAVASCRIPT",
				year: "2024",
				code: "",
				url: "",
			},
		],
	},
	skills: {
		id: "skills",
		title: "MY SKILLS",
		data: [
			"HTML",
			"CSS",
			"JAVASCRIPT",
			"TYPESCRIPT",
			"REACT JS",
			"NEXT JS",
			"EXPRESS JS",
			"NODE JS",
			"TAILWIND CSS",
			"GSAP",
			"FRAMER MOTION",
			"MONGODB",
			"POSTGRE SQL",
			"FIREBASE",
			"GIT",
			"LINUX",
		],
	},
	testimonials: [
		{
			name: "person one",
			img: "https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=600",
			desc: "Working with Anakin was an absolute pleasure! Their expertise in web development not only met but exceeded our expectations. They were responsive, attentive to detail, and delivered a website that perfectly encapsulated our brand's vision. We highly recommend Anakin for anyone seeking top-notch web development services.",
		},
		{
			name: "person two",
			img: "https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=600",
			desc: "Anakin is a true professional in the field of web development. Their ability to translate our ideas into a functional and visually stunning website was impressive. They demonstrated excellent communication skills throughout the project, ensuring that our needs were met every step of the way. We couldn't be happier with the results!",
		},
		{
			name: "person three",
			img: "https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=600",
			desc: "I can't speak highly enough of the experience I had working with Anakin. Their technical expertise and creative flair transformed our outdated website into a modern, user-friendly platform. Not only did they deliver on time and within budget, but they also provided valuable insights that enhanced the overall user experience. I wouldn't hesitate to recommend Anakin to anyone looking for top-quality web development services.",
		},
		{
			name: "person four",
			img: "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&w=600",
			desc: "Choosing Anakin for our web development project was one of the best decisions we made. From the initial consultation to the final delivery, they demonstrated a deep understanding of our requirements and consistently exceeded our expectations. Their professionalism, attention to detail, and commitment to excellence are commendable. We're thrilled with the results and look forward to collaborating with Anakin on future projects.",
		},
		{
			name: "person five",
			img: "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&w=600",
			desc: "Working with Anakin was a game-changer for our business. Their expertise in web development helped us revamp our online presence and attract more customers than ever before. Not only did they deliver a visually stunning website, but they also ensured that it was optimized for performance and user engagement. If you're looking for a talented and reliable web developer, look no further than Anakin.",
		},
	],
};
